### ISSUE TITLE
Add a lifetime to the secret

### ISSUE THREAD

**Issue by rafaelferreira6** [finiam/secrets.finiam.com#22]
When I'm creating a secret, I'd like to add a lifetime to it so that even if it's not opened, it's automatically destroyed after X hours/days/months.

**Comment by jfranciscosousa** [comment]
Can you add a simple design for this? I can tackle it tomorrow. We already have the backend tools for that.

**Comment by zediogoviana** [comment]
This has already been implemented by @jfranciscosousa . You can set a lifetime of 15min, 30min, 1h, or 6h.
Will close this but feel free to create a new issue if you think we need more options 👌
